# URL of the application
url = https://practicetestautomation.com/practice-test-login/

# Browser to use (chrome, firefox, edge)
browser = chrome

# Environment (e.g, Development, QA, Staging, Production)
environment = QA

username = student
password = Password123
headless = true

# Database configuration
db.url=jdbc:mysql://localhost:3306/testdb
db.username=root
db.password=pass

# API health check
api.health.urls=https://api.example.com/health,https://api.example.com/v2/health,https://auth.example.com/ping
#api.health.url.1=https://api.example.com/health
#api.health.url.2=https://api.example.com/v2/health
#api.health.url.3=https://auth.example.com/ping

