# URL of the application
app.url = https://the-internet.herokuapp.com/login

# Browser to use (chrome, firefox, edge)
browser = chrome

# Environment (e.g, Development, QA, Staging, Production)
environment = QA